theme: jekyll-theme-leap-day
plugins:
  - jekyll-seo-tag
show_downloads: false
github:
  index: https://perrinod.github.io/index
  about: https://perrinod.github.io/about
  projects: https://perrinod.github.io/projects
  resume: https://perrinod.github.io/resume
  competitions: https://perrinod.github.io/competitions